# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'secondWin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SecondWindow(object):
    def setupUi(self, SecondWindow):
        SecondWindow.setObjectName("SecondWindow")
        SecondWindow.resize(502, 539)
        self.centralwidget = QtWidgets.QWidget(SecondWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.activity1 = QtWidgets.QLabel(self.centralwidget)
        self.activity1.setGeometry(QtCore.QRect(30, 74, 311, 81))
        font = QtGui.QFont()
        font.setFamily("Artifakt Element Light")
        font.setPointSize(22)
        self.activity1.setFont(font)
        self.activity1.setStyleSheet("color: rgb(255, 255, 255);")
        self.activity1.setObjectName("activity1")
        self.generalName = QtWidgets.QLabel(self.centralwidget)
        self.generalName.setGeometry(QtCore.QRect(30, 14, 301, 61))
        font = QtGui.QFont()
        font.setFamily("Artifakt Element Light")
        font.setPointSize(36)
        self.generalName.setFont(font)
        self.generalName.setStyleSheet("color: rgb(255, 255, 255);")
        self.generalName.setObjectName("generalName")
        self.barActivity1 = QtWidgets.QProgressBar(self.centralwidget)
        self.barActivity1.setGeometry(QtCore.QRect(30, 144, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.barActivity1.setFont(font)
        self.barActivity1.setStyleSheet("QProgressBar {\n"
"    border-radius: 10px;\n"
"    background-color:rgb(85, 170, 255);\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(85, 85, 255);\n"
"}\n"
"")
        self.barActivity1.setProperty("value", 65)
        self.barActivity1.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.barActivity1.setObjectName("barActivity1")
        self.labelNivelAct1 = QtWidgets.QLabel(self.centralwidget)
        self.labelNivelAct1.setGeometry(QtCore.QRect(330, 84, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.labelNivelAct1.setFont(font)
        self.labelNivelAct1.setObjectName("labelNivelAct1")
        self.addButtonAct1 = QtWidgets.QPushButton(self.centralwidget)
        self.addButtonAct1.setGeometry(QtCore.QRect(375, 138, 41, 41))
        self.addButtonAct1.setStyleSheet("QPushButton {\n"
"    background-color: #2B5DD1;\n"
"    color: #FFFFFF;\n"
"    border-style: outset;\n"
"    padding: 2px;\n"
"    font: bold 20px;\n"
"    border-width: 6px;\n"
"    border-radius: 10px;\n"
"    border-color: #2752B8;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: lightgreen;\n"
"}")
        self.addButtonAct1.setObjectName("addButtonAct1")
        self.minusButtonAct1 = QtWidgets.QPushButton(self.centralwidget)
        self.minusButtonAct1.setGeometry(QtCore.QRect(430, 138, 41, 41))
        self.minusButtonAct1.setStyleSheet("QPushButton {\n"
"    background-color: #2B5DD1;\n"
"    color: #FFFFFF;\n"
"    border-style: outset;\n"
"    padding: 2px;\n"
"    font: bold 20px;\n"
"    border-width: 6px;\n"
"    border-radius: 10px;\n"
"    border-color: #2752B8;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(216, 25, 25);\n"
"}")
        self.minusButtonAct1.setObjectName("minusButtonAct1")
        self.labelBarMidAct1 = QtWidgets.QLabel(self.centralwidget)
        self.labelBarMidAct1.setGeometry(QtCore.QRect(140, 178, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Artifakt Element Light")
        font.setPointSize(14)
        font.setItalic(True)
        self.labelBarMidAct1.setFont(font)
        self.labelBarMidAct1.setObjectName("labelBarMidAct1")
        self.labelBarInfAct1 = QtWidgets.QLabel(self.centralwidget)
        self.labelBarInfAct1.setGeometry(QtCore.QRect(27, 178, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Artifakt Element Light")
        font.setPointSize(14)
        font.setItalic(False)
        self.labelBarInfAct1.setFont(font)
        self.labelBarInfAct1.setObjectName("labelBarInfAct1")
        self.labelBarSupAct1 = QtWidgets.QLabel(self.centralwidget)
        self.labelBarSupAct1.setGeometry(QtCore.QRect(332, 177, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Artifakt Element Light")
        font.setPointSize(14)
        font.setItalic(True)
        self.labelBarSupAct1.setFont(font)
        self.labelBarSupAct1.setObjectName("labelBarSupAct1")
        self.addButtonAct2 = QtWidgets.QPushButton(self.centralwidget)
        self.addButtonAct2.setGeometry(QtCore.QRect(375, 288, 41, 41))
        self.addButtonAct2.setStyleSheet("QPushButton {\n"
"    background-color: #2B5DD1;\n"
"    color: #FFFFFF;\n"
"    border-style: outset;\n"
"    padding: 2px;\n"
"    font: bold 20px;\n"
"    border-width: 6px;\n"
"    border-radius: 10px;\n"
"    border-color: #2752B8;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: lightgreen;\n"
"}")
        self.addButtonAct2.setObjectName("addButtonAct2")
        self.minusButtonAct2 = QtWidgets.QPushButton(self.centralwidget)
        self.minusButtonAct2.setGeometry(QtCore.QRect(430, 288, 41, 41))
        self.minusButtonAct2.setStyleSheet("QPushButton {\n"
"    background-color: #2B5DD1;\n"
"    color: #FFFFFF;\n"
"    border-style: outset;\n"
"    padding: 2px;\n"
"    font: bold 20px;\n"
"    border-width: 6px;\n"
"    border-radius: 10px;\n"
"    border-color: #2752B8;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(216, 25, 25);\n"
"}")
        self.minusButtonAct2.setObjectName("minusButtonAct2")
        self.barActivity2 = QtWidgets.QProgressBar(self.centralwidget)
        self.barActivity2.setGeometry(QtCore.QRect(30, 294, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.barActivity2.setFont(font)
        self.barActivity2.setStyleSheet("QProgressBar {\n"
"    border-radius: 10px;\n"
"    background-color:rgb(85, 170, 255);\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(85, 85, 255);\n"
"}\n"
"")
        self.barActivity2.setProperty("value", 65)
        self.barActivity2.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.barActivity2.setObjectName("barActivity2")
        self.labelBarInfAct2 = QtWidgets.QLabel(self.centralwidget)
        self.labelBarInfAct2.setGeometry(QtCore.QRect(27, 328, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Artifakt Element Light")
        font.setPointSize(14)
        font.setItalic(False)
        self.labelBarInfAct2.setFont(font)
        self.labelBarInfAct2.setObjectName("labelBarInfAct2")
        self.activity2 = QtWidgets.QLabel(self.centralwidget)
        self.activity2.setGeometry(QtCore.QRect(30, 224, 311, 81))
        font = QtGui.QFont()
        font.setFamily("Artifakt Element Light")
        font.setPointSize(22)
        self.activity2.setFont(font)
        self.activity2.setStyleSheet("color: rgb(255, 255, 255);")
        self.activity2.setObjectName("activity2")
        self.labelBarMidAct2 = QtWidgets.QLabel(self.centralwidget)
        self.labelBarMidAct2.setGeometry(QtCore.QRect(310, 328, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Artifakt Element Light")
        font.setPointSize(14)
        font.setItalic(True)
        self.labelBarMidAct2.setFont(font)
        self.labelBarMidAct2.setObjectName("labelBarMidAct2")
        self.labelBarSupAct2 = QtWidgets.QLabel(self.centralwidget)
        self.labelBarSupAct2.setGeometry(QtCore.QRect(332, 327, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Artifakt Element Light")
        font.setPointSize(14)
        font.setItalic(True)
        self.labelBarSupAct2.setFont(font)
        self.labelBarSupAct2.setObjectName("labelBarSupAct2")
        self.labelNivelAct2 = QtWidgets.QLabel(self.centralwidget)
        self.labelNivelAct2.setGeometry(QtCore.QRect(330, 234, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.labelNivelAct2.setFont(font)
        self.labelNivelAct2.setObjectName("labelNivelAct2")
        self.addButtonAct3 = QtWidgets.QPushButton(self.centralwidget)
        self.addButtonAct3.setGeometry(QtCore.QRect(375, 434, 41, 41))
        self.addButtonAct3.setStyleSheet("QPushButton {\n"
"    background-color: #2B5DD1;\n"
"    color: #FFFFFF;\n"
"    border-style: outset;\n"
"    padding: 2px;\n"
"    font: bold 20px;\n"
"    border-width: 6px;\n"
"    border-radius: 10px;\n"
"    border-color: #2752B8;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: lightgreen;\n"
"}")
        self.addButtonAct3.setObjectName("addButtonAct3")
        self.minusButtonAct3 = QtWidgets.QPushButton(self.centralwidget)
        self.minusButtonAct3.setGeometry(QtCore.QRect(430, 434, 41, 41))
        self.minusButtonAct3.setStyleSheet("QPushButton {\n"
"    background-color: #2B5DD1;\n"
"    color: #FFFFFF;\n"
"    border-style: outset;\n"
"    padding: 2px;\n"
"    font: bold 20px;\n"
"    border-width: 6px;\n"
"    border-radius: 10px;\n"
"    border-color: #2752B8;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(216, 25, 25);\n"
"}")
        self.minusButtonAct3.setObjectName("minusButtonAct3")
        self.barActivity3 = QtWidgets.QProgressBar(self.centralwidget)
        self.barActivity3.setGeometry(QtCore.QRect(30, 440, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.barActivity3.setFont(font)
        self.barActivity3.setStyleSheet("QProgressBar {\n"
"    border-radius: 10px;\n"
"    background-color:rgb(85, 170, 255);\n"
"}\n"
"QProgressBar::chunk{\n"
"    border-radius: 10px;\n"
"    background-color: rgb(85, 85, 255);\n"
"}\n"
"")
        self.barActivity3.setProperty("value", 65)
        self.barActivity3.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.barActivity3.setObjectName("barActivity3")
        self.labelBarInfAct3 = QtWidgets.QLabel(self.centralwidget)
        self.labelBarInfAct3.setGeometry(QtCore.QRect(27, 474, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Artifakt Element Light")
        font.setPointSize(14)
        font.setItalic(False)
        self.labelBarInfAct3.setFont(font)
        self.labelBarInfAct3.setObjectName("labelBarInfAct3")
        self.activity3 = QtWidgets.QLabel(self.centralwidget)
        self.activity3.setGeometry(QtCore.QRect(30, 370, 311, 81))
        font = QtGui.QFont()
        font.setFamily("Artifakt Element Light")
        font.setPointSize(22)
        self.activity3.setFont(font)
        self.activity3.setStyleSheet("color: rgb(255, 255, 255);")
        self.activity3.setObjectName("activity3")
        self.labelBarMidAct3 = QtWidgets.QLabel(self.centralwidget)
        self.labelBarMidAct3.setGeometry(QtCore.QRect(152, 473, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Artifakt Element Light")
        font.setPointSize(14)
        font.setItalic(True)
        self.labelBarMidAct3.setFont(font)
        self.labelBarMidAct3.setObjectName("labelBarMidAct3")
        self.labelBarSupAct3 = QtWidgets.QLabel(self.centralwidget)
        self.labelBarSupAct3.setGeometry(QtCore.QRect(332, 473, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Artifakt Element Light")
        font.setPointSize(14)
        font.setItalic(True)
        self.labelBarSupAct3.setFont(font)
        self.labelBarSupAct3.setObjectName("labelBarSupAct3")
        self.labelNivelAct3 = QtWidgets.QLabel(self.centralwidget)
        self.labelNivelAct3.setGeometry(QtCore.QRect(330, 380, 51, 51))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.labelNivelAct3.setFont(font)
        self.labelNivelAct3.setObjectName("labelNivelAct3")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 511, 581))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap(":/im2/background.png"))
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.label.raise_()
        self.activity1.raise_()
        self.generalName.raise_()
        self.barActivity1.raise_()
        self.labelNivelAct1.raise_()
        self.addButtonAct1.raise_()
        self.minusButtonAct1.raise_()
        self.labelBarMidAct1.raise_()
        self.labelBarInfAct1.raise_()
        self.labelBarSupAct1.raise_()
        self.addButtonAct2.raise_()
        self.minusButtonAct2.raise_()
        self.barActivity2.raise_()
        self.labelBarInfAct2.raise_()
        self.activity2.raise_()
        self.labelBarMidAct2.raise_()
        self.labelBarSupAct2.raise_()
        self.labelNivelAct2.raise_()
        self.addButtonAct3.raise_()
        self.minusButtonAct3.raise_()
        self.barActivity3.raise_()
        self.labelBarInfAct3.raise_()
        self.activity3.raise_()
        self.labelBarMidAct3.raise_()
        self.labelBarSupAct3.raise_()
        self.labelNivelAct3.raise_()
        SecondWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SecondWindow)
        QtCore.QMetaObject.connectSlotsByName(SecondWindow)

    def retranslateUi(self, SecondWindow):
        _translate = QtCore.QCoreApplication.translate
        SecondWindow.setWindowTitle(_translate("SecondWindow", "MainWindow"))
        self.activity1.setText(_translate("SecondWindow", "Code"))
        self.generalName.setText(_translate("SecondWindow", "NOmbre"))
        self.labelNivelAct1.setText(_translate("SecondWindow", "1"))
        self.addButtonAct1.setText(_translate("SecondWindow", "+"))
        self.minusButtonAct1.setText(_translate("SecondWindow", "-"))
        self.labelBarMidAct1.setText(_translate("SecondWindow", "6"))
        self.labelBarInfAct1.setText(_translate("SecondWindow", "1"))
        self.labelBarSupAct1.setText(_translate("SecondWindow", "10"))
        self.addButtonAct2.setText(_translate("SecondWindow", "+"))
        self.minusButtonAct2.setText(_translate("SecondWindow", "-"))
        self.labelBarInfAct2.setText(_translate("SecondWindow", "1"))
        self.activity2.setText(_translate("SecondWindow", "Code"))
        self.labelBarMidAct2.setText(_translate("SecondWindow", "6"))
        self.labelBarSupAct2.setText(_translate("SecondWindow", "10000"))
        self.labelNivelAct2.setText(_translate("SecondWindow", "1"))
        self.addButtonAct3.setText(_translate("SecondWindow", "+"))
        self.minusButtonAct3.setText(_translate("SecondWindow", "-"))
        self.labelBarInfAct3.setText(_translate("SecondWindow", "1"))
        self.activity3.setText(_translate("SecondWindow", "Hola"))
        self.labelBarMidAct3.setText(_translate("SecondWindow", "6"))
        self.labelBarSupAct3.setText(_translate("SecondWindow", "10"))
        self.labelNivelAct3.setText(_translate("SecondWindow", "1"))
import img2


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SecondWindow = QtWidgets.QMainWindow()
    ui = Ui_SecondWindow()
    ui.setupUi(SecondWindow)
    SecondWindow.show()
    sys.exit(app.exec_())
